global:
  scrape_interval: 5s
  scrape_timeout: 3s

  external_labels:
    monitor: 'feature-flag-monitoring'
  query_log_file: query_log_file.log

scrape_configs:
  - job_name: 'feature-flag-app'
    metrics_path: 'actuator/prometheus'
    scheme: 'http'
    static_configs:
      - targets: ['172.27.84.125:9292'] # 외부 로컬 
#      - targets: ['host.docker.internal:8080'] # 컨테이너 내부
