spring:
  config:
    import: application-adapter.yaml
  jpa:
    open-in-view: false

springdoc:
  api-docs:
    path: /api-docs
  cache:
    disabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

management:
  server:
    port: 9292
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          show-components: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
